---
title: "dusk_spl_repeatedmeasuresANOVA"
author: "Becca Van Hoeck"
date: "May 5, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Revised Analysis: 05/10/2021

Currently using two-way repeated measures ANOVA, followed by post-hoc pairwise comparisons
This accounts for the temporal autocorrelation, but likely doesn't account for pseudoreplication

```{r}
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(rstatix)

```

### Repeated measures ANOVA, replicates are daily average of SPL

```{r}
# Low Frequency

spl_table = read.csv("C:/Users/Becca/Documents/git/PAM_Habitat_Enhancement/low_dusk_spl_table_day_05-21.csv", header = TRUE)
spl_table$day = as.factor(spl_table$day)
spl_table$site = as.factor(spl_table$site)
spl_table$deploy = factor(spl_table$deploy, levels = c("May", "Jul", "Sep", "Oct", "Dec", "Apr"))

# Remove outlier and re-run
#spl_table$spl_db[8] = NA
# Removing outlier had no effect on result, so all data are retained

# Two-way Repeated measures ANOVA:

# Examine data
spl_table %>%
  group_by(site, deploy) %>%
  get_summary_stats(spl_db, type = "mean_sd")

# Check for outliers
spl_table %>%
  group_by(site, deploy) %>%
  identify_outliers(spl_db) # one outlier, but not extreme

# Check normality
spl_table %>%
  group_by(site,deploy) %>%
  shapiro_test(spl_db) 

ggqqplot(spl_table, "spl_db", ggtheme = theme_bw()) +
  facet_grid(deploy ~ site, labeller = "label_both") # pass normality test with qqplot

# Conduct ANOVA  
res.aov.low <- anova_test(
  data = spl_table, dv = spl_db, wid = day,
  within = c(site, deploy)
  )
get_anova_table(res.aov.low)

### identified a significant effect of site, deployment and their interaction. Deployment has the largest generalized effect size

# Effect of site at each time point
one.way <- spl_table %>%
  group_by(deploy) %>%
  anova_test(dv = spl_db, wid = day, within = site) %>%
  get_anova_table()
one.way
### Identified significant differences in all deployments except April (final deployment)

# Pairwise comparison between sites
pwc.low <- spl_table %>%
  group_by(deploy) %>%
  pairwise_t_test(
    spl_db ~ site, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc.low
### New reef (JJTug) is significantly louder in September
### New Reef and Established reef are the same in April


# Boxplot
lf_spl = ggplot(spl_table, aes(x = deploy, y = spl_db, fill = site))+ theme_bw()+
  geom_boxplot()+ #facet_wrap("Site")
  scale_fill_manual(values=c("gray71", "firebrick2"), )+
  scale_y_continuous(breaks=seq(90,120,5))+
  labs(x = "Deployment", y = expression("Dusk SPL (dB re 1 "*{mu}*"Pa)"))+
  theme(axis.text = element_text(size = 14), 
        strip.text = element_text(size = 16), 
        axis.title = element_text(size = 16), 
        legend.position = "none") 
        
lf_spl

```

# High Frequency

```{r}
spl_table_high = read.csv("high_dusk_spl_table_day_05-21.csv", header = TRUE)
spl_table_high$day = as.factor(spl_table_high$day)
spl_table_high$site = as.factor(spl_table_high$site)
spl_table_high$deploy = factor(spl_table_high$deploy, levels = c("May", "Jul", "Sep", "Oct", "Dec", "Apr"))


# Remove outlier and re-run
#spl_table_high$spl_db[51] = NA
# Removing outlier had no effect on result, so all data are retained

# testing two-way Repeated measures: 
spl_table_high %>%
  group_by(site, deploy) %>%
  get_summary_stats(spl_db, type = "mean_sd")

spl_table_high %>%
  group_by(site, deploy) %>%
  identify_outliers(spl_db) # one outlier, but not extreme

spl_table_high %>%
  group_by(site,deploy) %>%
  shapiro_test(spl_db) # Indra April and JJ Tug Dec violate normality

ggqqplot(spl_table_high, "spl_db", ggtheme = theme_bw()) +
  facet_grid(deploy ~ site, labeller = "label_both") # pass normality test with qqplot

# Conduct ANOVA  
# is pseudoreplication still a concern?
res.aov.high <- anova_test(
  data = spl_table_high, dv = spl_db, wid = day,
  within = c(site, deploy)
  )
get_anova_table(res.aov.high)

# Effect of site at each time point
one.way.high <- spl_table_high %>%
  group_by(deploy) %>%
  anova_test(dv = spl_db, wid = day, within = site) %>%
  get_anova_table() %>%
  adjust_pvalue(method = "bonferroni")
one.way.high

# Pairwise comparison between sites
pwc.high <- spl_table_high %>%
  group_by(deploy) %>%
  pairwise_t_test(
    spl_db ~ site, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc.high



# USe this to describe colonization trajectory of snapping shrimp
# Effect of time at each level of treatment
one.way2.high <- spl_table_high %>%
  group_by(site) %>%
  anova_test(dv = spl_db, wid = day, within = deploy) %>%
  get_anova_table() %>%
  adjust_pvalue(method = "bonferroni")
one.way2.high

# Pairwise comparisons between time points 
# doesn't work because 1 deployment has 8 samples instead of 7
pwc2.high <- spl_table_high %>%
  group_by(site) %>%
  pairwise_t_test(
    spl_db ~ deploy, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc2.high


hf_spl = ggplot(spl_table_high, aes(x = deploy, y = spl_db, fill = site))+ theme_bw()+
  geom_boxplot()+ #facet_wrap("Site")
  scale_fill_manual(values=c("gray71", "firebrick2"), )+
  labs(x = "Deployment", y = expression("Dusk SPL (dB re 1 "*{mu}*"Pa)"))+ 
  theme(axis.text = element_text(size = 14), 
        strip.text = element_text(size = 16), 
        axis.title = element_text(size = 16), 
        legend.position = c(0.9, 0.15))
hf_spl

#different seasonal changes
avgspl = spl_table_high %>%
  group_by(site, deploy) %>%
  summarize(meanSPL = mean(spl_db))
EstReef_diff = avgspl$meanSPL[2] - avgspl$meanSPL[1]
NewReef_diff = avgspl$meanSPL[8] - avgspl$meanSPL[7]

EstReef_diffFinal = avgspl$meanSPL[6] - avgspl$meanSPL[5]
NewReef_diffFinal = avgspl$meanSPL[12] - avgspl$meanSPL[11]
```

# plotting for publication

```{r}
ggarrange(lf_spl, hf_spl, labels = c("A", "B"), ncol = 2)

```

